CREATE TABLE Alumno (
    COD_ALUMNO int NOT NULL,
    NOMBRE varchar(30),
    FECHA_NACIMIENTO Date,
    COD_DIRECCION int not null,
    CONSTRAINT PK_ALUMNO PRIMARY KEY (COD_ALUMNO),
    CONSTRAINT FK_ALUMNO_COD_DIRECCION FOREIGN KEY (COD_DIRECCION) REFERENCES DIRECCION(COD_DIRECCION)
)
INSERT INTO ALUMNO VALUES (1, "Martin", 01-01-1981, 1)
INSERT INTO ALUMNO VALUES (2, "Laura", 02-02-1982, 2)
INSERT INTO ALUMNO VALUES (3, "Karina", 03-03-1983, 1)
INSERT INTO ALUMNO VALUES (4, "Daniel", 04-04-1984, 2)