CREATE TABLE Nota (
    COD_NOTA int NOT NULL,
    COD_ALUMNO int NOT NULL,
    PRIMER_NOTA FLOAT NOT NULL,
    SEGUNDA_NOTA FLOAT NOT NULL,
    PROMEDIO FLOAT NOT NULL,
    CONSTRAINT PK_NOTA PRIMARY KEY (COD_NOTA),
    CONSTRAINT FK_NOTA_COD_ALUMNO FOREIGN KEY (COD_ALUMNO) REFERENCES ALUMNO(COD_ALUMNO)
)
INSERT INTO Nota VALUES (1, 1, 6.0, 5.0, 5.5)
